FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore "src/QuantaCandle.TradeRecorder/QuantaCandle.TradeRecorder.csproj"

RUN dotnet publish "src/QuantaCandle.TradeRecorder/QuantaCandle.TradeRecorder.csproj" \
    --configuration Release \
    --output /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/runtime:10.0 AS runtime

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "tr.dll"]
